[package]
name = "tac"
version = "0.1.1"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
description = "Print lines from file in reverse order"
homepage = "https://github.com/neosmart/tac"
repository = "https://github.com/neosmart/tac"
readme = "README.md"
keywords = ["tac", "reverse"]
categories = ["command-line-utilities"]
license = "MIT"

[dependencies]
memmap = "0.5"
simple-signal = "1.1"
try_print = "0.0.1"
uuid = { version = "0.4", features = ["v4"] } 
